export const QUERY_KEYS = {
  RATE_CONFIGURATION: 'RATE_CONFIGURATION',
  COF_BASE_RATE: 'COF_BASE_RATE',
  COF_BASIS_POINTS: 'COF_BASIS_POINTS',
  COF_BASIS_SWAP: 'COF_BASIS_SWAP',
  COF_DATA: 'COF_DATA',
  SURCHARGES_LIST: 'SURCHARGES_LIST',
  SURCHARGE: 'SURCHARGE',
  PROFORMA_CONFIG: 'PROFORMA_CONFIG',
  PROFORMA_LIST: 'PROFORMA_LIST',
  PROFORMA_SURCHARGE: 'PROFORMA_SURCHARGE',
};